import Head from "next/head";
import { Inter } from "next/font/google";
import MeetupList from "@/components/meetups/MeetupList";

const inter = Inter({ subsets: ["latin"] });
const DUMMY=[
    {
        id:1,
        title:"This is a DUMMY",
        image:"https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Startrails_above_Gunung_Bromo_-_Indonesia.jpg/2560px-Startrails_above_Gunung_Bromo_-_Indonesia.jpg",
        address:"Da Lat",
        description:"This is a DUMMY DESCRIPTION",
    },
    {
        id:2,
        title:"This is a DUMMY 2",
        image:"https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Startrails_above_Gunung_Bromo_-_Indonesia.jpg/2560px-Startrails_above_Gunung_Bromo_-_Indonesia.jpg",
        address:"Lam Dong",
        description:"This is a DUMMY DESCRIPTION",
    }
]

export default function Home(props) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <MeetupList meetups={props.meetups} />
          <p>{props.test}</p>
    </>
  );
}
export async function getStaticProps() {
    return {
        props: {
            meetups:DUMMY,
            revalidate: 5,
        },
    }
}